# Site settings
baseurl: ""
url: "http://gahayashi.github.io"
version: "0.1.0"
permalink: /:year/:month/:day/:title/

# Blog metas
title: Gabriele Hayashi
author: Gabriele Hayashi
email: gabriele.hayashi@gmail.com
description: |
  Um pseudo-filósofo, programador de meia-tigela e comediante nas horas vagas, que são todas as horas.

twitter_username: gahayashi
github_username: gahayashi

# Build settings
markdown: kramdown
source: source
destination: build